#!/usr/bin/env bash
# Integration tests for the batch import parsers (SDF, CSV, TXT, SMI, XYZ).
# Run from the repository root: ./tests/test_batch_import.sh
#
# Each test creates a temporary fixture file in $OUT_DIR, runs the CLI with
# --batch-*, and asserts the expected number of jobs succeed.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="$(mktemp -d /tmp/easynmr_batch_test_XXXXXX)"
trap 'rm -rf "$OUT_DIR"' EXIT

PASS=0
FAIL=0

_TMP_N=0
tmp_file() {
    # tmp_file <suffix>  — returns a unique path inside OUT_DIR
    _TMP_N=$((_TMP_N + 1))
    echo "${OUT_DIR}/fixture_${_TMP_N}${1}"
}

run_batch() {
    # run_batch <flag> <file> <expected_ok>
    local flag="$1" file="$2" expected="$3" label
    label="$(basename "$file")"
    local output
    output=$(EASYSPECTRA_XTB=__none__ ./build/easynmr \
        "$flag" "$file" \
        --workflow nmr --level low \
        --output-dir "$OUT_DIR" 2>&1) || true
    local ok
    ok=$(echo "$output" | grep -c '^\[OK\]' || true)
    if [ "$ok" -eq "$expected" ]; then
        echo "  PASS  $label  ($ok/$expected ok)"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  $label  (got $ok ok, expected $expected)"
        echo "        output: $output"
        FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
echo "[1/7] SMILES file (.smi) — 3 molecules"
_F=$(tmp_file .smi)
printf "CCO ethanol\nCC(=O)O acetic_acid\nc1ccccc1 benzene\n" > "$_F"
run_batch --batch-smi "$_F" 3

# ---------------------------------------------------------------------------
echo "[2/7] CSV with header (smiles,name) — 3 molecules"
_F=$(tmp_file .csv)
printf "smiles,name\nCCO,ethanol\nCC(=O)O,acetic_acid\nc1ccccc1,benzene\n" > "$_F"
run_batch --batch-csv "$_F" 3

# ---------------------------------------------------------------------------
echo "[3/7] CSV with no header — 2 molecules (col 0 = SMILES, col 1 = name)"
_F=$(tmp_file .csv)
printf "CCN,ethylamine\nCCCC,butane\n" > "$_F"
run_batch --batch-csv "$_F" 2

# ---------------------------------------------------------------------------
echo "[4/7] TXT tab-delimited with header — 2 molecules"
_F=$(tmp_file .txt)
printf "smiles\tname\nCCO\tethanol\nCCN\tethylamine\n" > "$_F"
# .txt dispatches through parse_batch_file, which tries CSV then SMI
run_batch --batch-smi "$_F" 2

# ---------------------------------------------------------------------------
echo "[5/7] SDF file — 2 molecules (generated by RDKit)"
_F=$(tmp_file .sdf)
python3 - "$_F" << 'PY_EOF'
import sys
from rdkit import Chem
from rdkit.Chem import AllChem
mols = [("ethanol", "CCO"), ("acetic_acid", "CC(=O)O")]
w = Chem.SDWriter(sys.argv[1])
for name, smi in mols:
    m = Chem.AddHs(Chem.MolFromSmiles(smi))
    m.SetProp("_Name", name)
    AllChem.EmbedMolecule(m, randomSeed=42)
    w.write(m)
w.close()
PY_EOF
run_batch --batch-sdf "$_F" 2

# ---------------------------------------------------------------------------
echo "[6/7] Multi-XYZ — 2 molecules"
_F=$(tmp_file .xyz)
cat > "$_F" << 'XYZ_EOF'
9
ethanol
C   0.000   0.000   0.000
C   1.531   0.000   0.000
O   2.051   1.176   0.000
H  -0.390   1.017   0.000
H  -0.390  -0.510   0.882
H  -0.390  -0.510  -0.882
H   1.921  -0.510   0.882
H   1.921  -0.510  -0.882
H   2.999   1.076   0.000
5
methane
C   0.000   0.000   0.000
H   0.630   0.630   0.630
H  -0.630  -0.630   0.630
H  -0.630   0.630  -0.630
H   0.630  -0.630  -0.630
XYZ_EOF
run_batch --batch-xyz "$_F" 2

# ---------------------------------------------------------------------------
echo "[7/7] SMILES file with comment lines and blank lines (robustness)"
_F=$(tmp_file .smi)
printf "# comment\n\nCCO ethanol\n\n# another\nCC(=O)O acetic_acid\n" > "$_F"
run_batch --batch-smi "$_F" 2

# ---------------------------------------------------------------------------
echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
